const RecipePosts = {
    "steak-donburi": {
      dish: "Steak Donburi",
      image1: "/img/steakdonburi.jpg",
      ingredient1:"1lb ribeye steak",
      ingredient2:"sweet yellow onion",
      ingredient3:"green onion",
      ingredient4:"egg yolk",
      ingredient5:"rice",
      ingredient6:"soy sauce",
      ingredient7:"kombu",
      ingredient8:"bonito flakes",
      ingredient9:"sugar",
      ingredient10:"wasabi",
      ingredient11:"yuzu",
      ingredient12:"sesame oil",
      instruction1:"Cook Rice: 1 cup of rice = 1 cup of water. Follow this ratio and your rice won’t come out undercooked or mushy. I will note though that some rice cooker are manufactured differently so you may need to adjust this ratio as needed but this is the default. Also feel free to use a light dashi stock instead of water to cook the rice!",
      instruction2:"Make Shoyu Sauce: In a sauce pan, bring equal parts soy sauce and mirin to a simmer. Torch 1-2 pieces of kombu and put into sauce along with a handful of bonito flakes and sugar to taste. Simmer for a few more minutes before taking it off heat and letting it cool.",
      instruction3:"Sear Steak: Make sure the steak is at room temp and is patted dry. Heat up oil in pan and sear steak on all sides. No need to season since we will use a sauce to flavor the steak. Once steak hits 120 degrees, take off heat and let it rest. (cook longer if you want a medium or higher cook on it) Once rested, slice the steak into strips. Optional: place on tray and put shoyu sauce on. Use a blowtorch and torch the steak.",
      instruction4:"Caramelize Onions: Julienne a whole onion (it may seem like a lot but it will reduce in size while you cook) and cook on low/medium heat. When it’s golden and almost jam like consistency, put it aside.",
      instruction5:"Cure Egg Yolk: Separate some egg yolks and place into the cooled shoyu sauce. Let it cure overnight for best results but a few hours should do the trick as well.",
      instruction6:"Make onion/scallion mix: Dice some onion, and chop some green onions and put into ice water. After 5 minutes, drain and put in separate bowl. Put 2 toothpaste amount of wasabi, 1 spoon of yuzu, and 1/2 spoon of sesame oil and mix.",
      instruction7:"Assemble Dish: 1 scoop of rice in a spherical shape, topped with the caramelized onions. put slices of steak around the rice (put sauce on if you haven’t already). Leave room on the middle top for the yolk to sit on. Sprinkle the onion/scallion mix and that’s it! Enjoy :)",
      pic2: "/img/Recipes/Steak-Donburi/rice_onions.jpg",
      pic3: "/img/Recipes/Steak-Donburi/steak.jpg",
      pic4: "/img/Recipes/Steak-Donburi/egg.jpg",
    },
    "random": {
        dish: "testing",
        image1: "/img/steakdonburi.jpg",
        ingredient1:"1lb ribeye steak",
        ingredient2:"sweet yellow onion",
        ingredient3:"green onion",
        ingredient4:"egg yolk",
        ingredient5:"rice",
        ingredient6:"soy sauce",
        ingredient7:"kombu",
        ingredient8:"bonito flakes",
        ingredient9:"sugar",
        ingredient10:"wasabi",
        ingredient11:"yuzu",
        ingredient12:"sesame oil",
        instruction1:"Cook Rice: 1 cup of rice = 1 cup of water. Follow this ratio and your rice won’t come out undercooked or mushy. I will note though that some rice cooker are manufactured differently so you may need to adjust this ratio as needed but this is the default. Also feel free to use a light dashi stock instead of water to cook the rice!",
        instruction2:"Make Shoyu Sauce: In a sauce pan, bring equal parts soy sauce and mirin to a simmer. Torch 1-2 pieces of kombu and put into sauce along with a handful of bonito flakes and sugar to taste. Simmer for a few more minutes before taking it off heat and letting it cool.",
        instruction3:"Sear Steak: Make sure the steak is at room temp and is patted dry. Heat up oil in pan and sear steak on all sides. No need to season since we will use a sauce to flavor the steak. Once steak hits 120 degrees, take off heat and let it rest. (cook longer if you want a medium or higher cook on it) Once rested, slice the steak into strips. Optional: place on tray and put shoyu sauce on. Use a blowtorch and torch the steak.",
        instruction4:"Caramelize Onions: Julienne a whole onion (it may seem like a lot but it will reduce in size while you cook) and cook on low/medium heat. When it’s golden and almost jam like consistency, put it aside.",
        instruction5:"Cure Egg Yolk: Separate some egg yolks and place into the cooled shoyu sauce. Let it cure overnight for best results but a few hours should do the trick as well.",
        instruction6:"Make onion/scallion mix: Dice some onion, and chop some green onions and put into ice water. After 5 minutes, drain and put in separate bowl. Put 2 toothpaste amount of wasabi, 1 spoon of yuzu, and 1/2 spoon of sesame oil and mix.",
        instruction7:"Assemble Dish: 1 scoop of rice in a spherical shape, topped with the caramelized onions. put slices of steak around the rice (put sauce on if you haven’t already). Leave room on the middle top for the yolk to sit on. Sprinkle the onion/scallion mix and that’s it! Enjoy :)",
        pic2: "/img/Recipes/Steak-Donburi/rice_onions.jpg",
        pic3: "/img/Recipes/Steak-Donburi/steak.jpg",
        pic4: "/img/Recipes/Steak-Donburi/egg.jpg",
      },
};

export default RecipePosts;