const BlogPosts = {
    "steak-donburi": {
      dish: "Steak Donburi",
      image1: "/img/Blogs/Steak-Donburi/steakdonburi.jpg",
      intro: "This is by far the dish I am most proud of so far. It’s honestly such a simple dish but through multiple iterations, I’ve been able to elevate it just a tiny bit each time. The best part about this dish is how versatile it is. At it's simplest form, it's a quick 5 minute bite but with a little more time and care, can turn into a showstopping dish for any occasion. Although this dish, at its peak complexity, contains many elements, I promise the work is definitely worth it. I’ve probably spent 1-2 years experimenting on this dish and I probably will make another version in the future but for now, I’m super excited to share my experience cooking this dish. Keep reading for entertainment or go and check the recipe out!",
      image2: "/img/Blogs/Steak-Donburi/steak.jpg",
      image3: "/img/Blogs/Steak-Donburi/egg.jpg",
      image4: "/img/Blogs/Steak-Donburi/rice_onions.jpg",
      body: "The first time I made this dish, it was probably midnight and I just really wanted to eat whatever I could find in my fridge. I got some left over rice, stir fried some onions, sliced some leftover steak, and drizzled some Bachan’s Japanese bbq sauce and called it good. And if I’m being honest, it’s probably how I would make it most days. But if you got the time to cook and want to treat yourself, your friends, or family to something tasty; I fully recommend taking the extra steps to make this dish next level.",
      keynote1: "Steak: Any cut of meat will do, but make sure it’s at least an inch thick so you have room to get a good sear on all sides without overcooking the middle. Unless you like well cooked meat, in which case, you should just buy the cheapest piece of meat you can find (jk, eat it however you like it’s your food lol).",
      keynote2:"Egg yolk: This is totally optional but I think it adds a nice creamy texture and gives the dish more color. You can just use a plain egg yolk or if you have some extra time, place the egg yolk in shoyu and let it cure overnight.",
      keynote3:"onions: low and slow is key! If you want that natural sweet flavor from the onions and get that golden color, you’re going to need to be patient. Cooking at too high of a heat will cause the onions to burn and dry out. Just cook at a low-medium heat and constantly stir so the onions cook evenly.",
      keynote4:"Shoyu sauce: Bachan’s bbq sauce is a fool proof sauce to make this dish taste good. But if you want to make everything from scratch, boil some soy, mirin, sugar, bonito flakes, and torched kombu. Let it cool and you got yourself a tare sauce that’ll give the dish more umami depth. (bonus tip: you can use this same sauce to cure your yolks in too!)",
      keynote5:"Scallions/onions: Less is more and simple does the trick in most cases. But I found this to be a very simple and light topping that brings the dish together. Soak some scallions and diced onions in ice water to get rid of some of the raw spiciness, drain and then put some wasabi, yuzu, and sesame oil and sprinkle it on top!",
      conclusion: "This is something I can probably eat 3-5 times a week easily and it’s so easy to make. And so many shortcuts you can take without compromising flavor if you’re short on time. And if you have the time, these steps just take it up another notch. If there’s any dish on this site you should try making it’s this one! Go try it out yourself and let me know how it goes :)",
    },
    "sake-blossom": {
      dish: "Sake Blossom",
      image1: "/img/Blogs/Sake-Blossom/Sake.jpg",
      intro: "If you're feeling extra artistic for your next meal and craving something that tastes as good as it looks visually, look no further. This sashimi appetizer is super light and has a nice refreshing taste with citric notes. Definetly still in the works and I already have some ideas for the next iteration but it already tastes so good I had to share LOL.",
      image2: "/img/Blogs/Sake-Blossom/wrap.jpg",
      image3: "/img/Blogs/Sake-Blossom/bird-eye.jpg",
      image4: "/img/Blogs/Sake-Blossom/wrap-close.jpg",
      body: "I won't lie, I got this idea from IG as I was doom scrolling at 2 in the morning but if losing sleep means I get to try making dishes as tasty as this, it may lowkey be worth it. (jk I need to fix my sleep schedule bad) Honestly, the best part of this dish is probably the minimal ingredients and time needed to make it. The creamy and melting texture of the salmon goes really well with the crispiness of the radish and microgreens. The ponzu sauce drizzled on top adds a nice citrus flavor as well. The tobiko honestly didn't do anything taste wise and can be left out but it does add a fun texture.",
      keynote1: "For the radish, use a mandoline to get those super thin slices. My mandoline actually cut it thicker than I wanted which made it difficult to get that flower effect when wrapping with the salmon. Idealy, the radish slices should be see through/paper thin.",
      keynote2:"I always thought microgreens were a waste of money because of the lack of taste and it honestly just felt like an aesthetic rather than adding flavor to a dish. These bean sprout microgreens might be an exception though. I wouldn't go as overboard as I did in the pic, but adding a handful adds a bitter flavor that goes suprisingly well with the other components of the dish.",
      keynote3:"Sushi grade fish! And even if it is sushi grade, I recommend taking tapeworm pills for anyone that consumes raw fish. Another tip, lightly freeze the fish before slicing as it will give you nicer clean cuts.",
      keynote4:"You can use store bought ponzu sauce or if you're extra like me, mix soy sauce and yuzu, 2:1 ratio.",
      conclusion: "If you're in the mood for a lighter meal or wanting a quick bite before a main, this simple dish will definetly leave your tastbuds satisfied!",
    },
    "mala-shrimp": {
      dish: "Shrimp Toast w/ Mala Cream",
      image1: "/img/Blogs/mala-shrimp/malashrimp.jpg",
      intro: "Ok so the title may be a little misleading. It's inspired by the Hong Kong dish but there were a few fails during my attempt to make this. So instead of toast, I used Trader Joe's hashbrown as a subsitution. Don't need to recreate the wheel right? I'm just coping tbh, I'll take the L and try again later but I'm going to need some time to recover from dish trauma cause I spent an unholy amount of time making this.",
      image2: "/img/Blogs/mala-shrimp/shrimp.jpg",
      image3: "/img/Blogs/mala-shrimp/pave.jpg",
      image4: "/img/Blogs/mala-shrimp/tuile.jpg",
      body: "When brainstorming for this dish, I deconstructed the shrimp toast dish down to single elements, toast and shrimp paste. Pretty hard to mess that up, right? And somehow I managed to do that. I wanted to try using a potato pave (thinly sliced potato stacked and frozen overnight, then cut and fried) as the toast and chop up shrimp instead of grinding it into a paste to give it more texture. My first mistake was not accounting for how to get the chopped shrimp to spread evenly and stick to my potato pave. My second mistake was tryng to make potato pave for the first time and use it as a key element in another dish. So many things went wrong; the potato pave fell apart as it was being fried, the shrimp detached itself from the potato, and I completely forgot about the different cooking times and ended up burning the potato and overcooking the shrimp and giving it a rubbery texture. Luckily, I had some hashbrowns in the freezer and I grounded up the remaining shrimp and it turned out relatively ok for the amount of chaos that occured beforehand. On the bright side, the tuile and mala cream sauce I created came out so good and it made the mess more bareable. Like I said before, probably won't make this again for awhile but I will attempt it again once I recover so be on the look out for a redemption blog!",
      conclusion: "Like I said before, probably won't make this again for awhile but I will attempt it again once I recover so be on the look out for a redemption blog!",
    },
    "steak-taco": {
      dish: "Steak Tacos",
      image1: "/img/Blogs/Steak-Taco/tacos.jpg",
      intro: "Miso marinated steak, crunchy cabbage, sweet and tangy apple pico de gallo, and a wasabi mayo to bring it all together. These japanese fusion tacos are actually so good and your taste buds will thank you everytime you make this. I'm still learning to plate so sorry in advance if it looks like elementary school art lol. Lowkey better plating than Cheesecake Factory though, but that's just my opinion.",
      image2: "/img/Blogs/Steak-Taco/eat-taco.jpg",
      image3: "/img/Blogs/Steak-Taco/apple.jpg",
      image4: "/img/Blogs/Steak-Taco/tacos2.jpg",
      body: "Gordan Ramsey made a video 10 years ago that I remember watching and wanting to try. But back then, I had 0 cooking skills or a desire to cook. All I wanted to do was eat (big back activities, I know) But I randomly came across the video again and I decided to give it a try with a few minor tweaks. I wanted to keep the crispiness of the cabbage so I didn't add any type of dressing so that the crunch of the cabbage could be retained. Instead, I added a pico de gallo with apples instead of tomatoes to give it the tangy flavor the dressing would have given. The wasabi mayo was interesting but I think I got the ratio wrong cause it tasted too oily. Overall, the taste was as good as I was expecting and with a few more tries under my belt, I'm sure it'll taste even better the next time I make it.",
      keynote1:"Resting the steak is crucial as it will help keep all the steak juices inside and not seep out. Rest the steak for about 4-5 minutes after taking it off the heat for best results. Also make sure the steak is pat dry before searing or you will get an inconsistent cook as the moisture from the steak can cause the meat to boil and create gray spots.",
      keynote2:"For the mayo, I used 3 to 1 ratio of oil to egg but I think a 2 to 1 ratio is more appropriate. Add as much wasabi as you want (this acts as the dijon mustard seeds you would normally put in mayo) and a splash of yuzu (subsitute for lemon). Ramsey uses store bought mayo but that's something I will never eat lol, and homemade just tastes so much better.",
      keynote3:"For the tortillas, Ramsey cooks them directly on the fire and molds them by taking it off the heat and immediately wrapping around a cylinder. I tried doing this with store bought tortillas but they were too thick so they ended up going flat after a few seconds. If trying to recreate the taco shell shape, use very thin tortillas.",
      keynote4:"Apples when exposed to oxygen for too long will cause discolorment. Although it doesn't affect the taste, it isn't very appealing visually. My suggestion is to chop up the apples last and immediately put some citrus (lemon, lime, or yuzu) which will help prevent discolorment.",
      conclusion: "After making these tacos, I wished I had got into cooking earlier but I guess better late than never haha!",
    },
    "blog-template": {
      dish: "",
      image1: "",
      intro: "",
      image2: "",
      image3: "",
      image4: "",
      body: "",
      keynote1: "",
      keynote2:"",
      keynote3:"",
      keynote4:"",
      keynote5:"",
      conclusion: "",
    },
};

export default BlogPosts;